services:
  psql_db:
    image: postgres:15-alpine
    container_name: nhietdien_posgres15_alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - nhietdien_project_data:/var/lib/postgresql/data
      - ./nhietdien.sql:/docker-entrypoint-initdb.d/nhietdien.sql
    networks:
      - nhietdien-network
  nhietdien-backend:
    build: ./backend
    container_name: nestjs_nhietdien
    restart: always
    depends_on:
      - psql_db
    env_file:
      - .env
    networks:
      - nhietdien-network
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_nhietdien
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nhietdien-backend
    networks:
      - nhietdien-network
networks:
  nhietdien-network:
    driver: bridge

volumes:
  nhietdien_project_data:
